version: '3.2'

services:
  flask:
    build: ./backend
    # image: helloitsjoe/blackjack-python-backend:latest
    volumes:
      - ./backend:/app
    ports:
      - '5000:5000'

  frontend:
    # image: helloitsjoe/blackjack-preact-frontend:latest
    build:
      context: ./frontend
      args:
        LOCAL: 'true'
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - '80:80'
