version: '2.0'

services:
  flask:
    build: ./game
    image: blackjack-python-backend
    ports:
      - 5000:5000

  frontend:
    build: ./frontend
    image: blackjack-preact-frontend
    ports:
      - 80:80
