version: '2.0'

services:
  flask:
    build: ./game
    image: helloitsjoe/blackjack-python-backend:latest
    ports:
      - 5000:5000

  frontend:
    build: ./frontend
    image: helloitsjoe/blackjack-preact-frontend:latest
    ports:
      - 80:80
