version: '3.2'

services:
  redis:
    # TODO: Look into Redis warnings
    image: redis:6
    ports:
      - '6379:6379'

  flask:
    # image: helloitsjoe/blackjack-python-backend:latest
    build:
      context: ./backend
    depends_on:
      - redis
    environment:
      - LOCAL
    # Enable volumes to watch for local changes
    # volumes:
    #   - ./backend:/app
    ports:
      - '5000:5000'

  frontend:
    # image: helloitsjoe/blackjack-preact-frontend:latest
    build:
      context: ./frontend
      args:
        LOCAL: 'true'
    depends_on:
      - flask
    # Enable volumes to watch for local changes
    # volumes:
    #   - ./frontend/dist:/usr/share/nginx/html
    ports:
      - '80:80'
