version: '3.2'

services:
  flask:
    build: ./backend
    image: helloitsjoe/blackjack-python-backend:latest
    ports:
      - '5000:5000'

  frontend:
    build: ./frontend
    # image: helloitsjoe/blackjack-preact-frontend:latest
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - '80:80'
