version: '2.0'

services:
  flask:
    build: ./game
    image: python-blackjack-test
    ports:
      - 5000:5000

  frontend:
    build: ./frontend
    image: preact-blackjack-test
    ports:
      - 80:80
